version: '3.9'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: changeme

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  postgres-data:
